version: '3.8'

services:
  orderservice:
    build: ./OrderService
    container_name: orderservice
    ports:
      - '8081:8081'
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  shippingservice:
    build: ./ShippingService
    container_name: shippingservice
    ports:
      - '8082:8082'
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  paymentservice:
    build: ./PaymentService
    container_name: paymentservice
    ports:
      - '8083:8083'
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
